default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

development:
  adapter: postgresql
  database: job_scheduler
  adapter: postgis
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 6969

production:
  <<: *default
  database: db/production.sqlite3

test:
  adapter: postgresql
  database: rails_test
  adapter: postgis
  username: rails
  password: password
  host: localhost
  port: 5432

