name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main", "epic/phase-one" ]
  pull_request:
    branches: [ "main", "epic/phase-one" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:13-3.4
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
          FRONTEND_URL: http://localhost:8080
          jwt_secret_key: '0123456789'
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgis://rails:password@localhost:5432/rails_test"
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Install Gems
        run: |
          gem install bundler
          bundle install
      - name: Create rails credential key
        run: bin/rails credentials:edit
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bin/rails test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Install brakeman
        run: gem install brakeman
      - name: Install rubocop
        run: gem install rubocop
      - name: Install bundler-audit
        run: gem install bundler-audit
      - name: Security audit dependencies
        run: bundle audit check --update
      - name: Security audit application code
        run: brakeman -q -w2
      - name: Lint Ruby files
        run: rubocop --parallel -l
